Settings
sviridchik/diploma pull request #3
Opened 2023-04-24 09:21 UTC by sviridchik

done patient and guardian setting

2023-04-24 09:27 UTC, sviridchik commented
<img width="1440" alt="Снимок экрана 2023-04-24 в 12 14 08" src="https://user-images.githubusercontent.com/52378018/233955562-4394d117-e09a-4f73-a974-ca58257b176d.png">
<img width="1440" alt="Снимок экрана 2023-04-24 в 12 13 50" src="https://user-images.githubusercontent.com/52378018/233955578-c874dc4f-0161-4eba-9b66-581dd4425c3a.png">

**POST {{local}}/managment/patients/**
`{
  "first_name": "testSet",
  "last_name": "testovich",
  "age": 22,
  "phone": 375447990822
}`


**GET {{local}}/managment/settings/**
`[
    {
        "id": 2,
        "color": "white",
        "font": 14,
        "city": "Minsk",
        "language": "RUSSIAN",
        "patient": 7
    }
]`

2023-04-24 09:28 UTC, sviridchik commented
<img width="1440" alt="Снимок экрана 2023-04-24 в 12 15 43" src="https://user-images.githubusercontent.com/52378018/233956736-638e6ec8-ebb5-4cf0-badf-1f2a46874b1f.png">
<img width="1440" alt="Снимок экрана 2023-04-24 в 12 18 57" src="https://user-images.githubusercontent.com/52378018/233956741-7c681026-75f7-4c05-ad19-c210d0591af0.png">

**POST {{local}}/managment/guardians/**

`{
  "first_name": "guardianSet",
  "last_name": "testovich",
  "age": 22,
  "phone": 375440943822
}`

`{
    "id": 6,
    "user": {
        "id": 10,
        "email": "",
        "username": "qwe"
    },
    "first_name": "guardianSet",
    "last_name": "testovich",
    "phone": 375440943822
}`

**GET {{local}}/managment/settings_guard/**
`[
    {
        "id": 1,
        "language": "RUSSIAN",
        "theme": "white",
        "guardian": 6
    }
]`

2023-04-25 08:15 UTC, sviridchik commented
<img width="1440" alt="Снимок экрана 2023-04-25 в 11 14 45" src="https://user-images.githubusercontent.com/52378018/234216280-fdb54df0-63eb-46d0-89a1-203216c8d869.png">

2023-04-25 08:40 UTC, sviridchik commented
**GET {{local}}/statistic/report/?ward=5**

<img width="1440" alt="Снимок экрана 2023-04-25 в 11 40 07" src="https://user-images.githubusercontent.com/52378018/234222514-d6d34a8f-4307-47d4-88e0-1616baa217c0.png">

`{
    "taken": [
        {
            "id": 1,
            "med": {
                "id": 24,
                "title": "ярина",
                "dose": 1.0,
                "dose_type": "pcs",
                "type": "pill",
                "strict_status": false,
                "food": "Before meals",
                "patient": 5,
                "schedule": 32
            },
            "date": "2023-04-24T14:18:11.976719+03:00",
            "is_late": true,
            "report": false,
            "patient": 5
        },
        {
            "id": 2,
            "med": {
                "id": 25,
                "title": "юритмик",
                "dose": 1.0,
                "dose_type": "ml",
                "type": "ampule",
                "strict_status": false,
                "food": "Before meals",
                "patient": 5,
                "schedule": 33
            },
            "date": "2023-04-24T14:21:48.921206+03:00",
            "is_late": true,
            "report": false,
            "patient": 5
        },
        {
            "id": 3,
            "med": {
                "id": 26,
                "title": "тотема",
                "dose": 3.0,
                "dose_type": "ml",
                "type": "ampule",
                "strict_status": false,
                "food": "No matter",
                "patient": 5,
                "schedule": 34
            },
            "date": "2023-04-24T14:22:41.247434+03:00",
            "is_late": true,
            "report": false,
            "patient": 5
        },
        {
            "id": 4,
            "med": {
                "id": 27,
                "title": "missed",
                "dose": 34.0,
                "dose_type": "ml",
                "type": "pill",
                "strict_status": false,
                "food": "While eating",
                "patient": 5,
                "schedule": 35
            },
            "date": "2023-04-24T15:02:50.260921+03:00",
            "is_late": true,
            "report": false,
            "patient": 5
        },
        {
            "id": 5,
            "med": {
                "id": 27,
                "title": "missed",
                "dose": 34.0,
                "dose_type": "ml",
                "type": "pill",
                "strict_status": false,
                "food": "While eating",
                "patient": 5,
                "schedule": 35
            },
            "date": "2023-04-24T15:08:08.016498+03:00",
            "is_late": true,
            "report": false,
            "patient": 5
        },
        {
            "id": 6,
            "med": {
                "id": 27,
                "title": "missed",
                "dose": 34.0,
                "dose_type": "ml",
                "type": "pill",
                "strict_status": false,
                "food": "While eating",
                "patient": 5,
                "schedule": 35
            },
            "date": "2023-04-24T15:10:26.455849+03:00",
            "is_late": true,
            "report": false,
            "patient": 5
        }
    ],
    "missed": [
        {
            "id": 1,
            "med": {
                "id": 27,
                "title": "missed",
                "dose": 34.0,
                "dose_type": "ml",
                "type": "pill",
                "strict_status": false,
                "food": "While eating",
                "patient": 5,
                "schedule": 35
            },
            "date": "2023-04-24T15:16:37.700610+03:00",
            "is_informed": false,
            "patient": 5
        },
        {
            "id": 2,
            "med": {
                "id": 27,
                "title": "missed",
                "dose": 34.0,
                "dose_type": "ml",
                "type": "pill",
                "strict_status": false,
                "food": "While eating",
                "patient": 5,
                "schedule": 35
            },
            "date": "2023-04-24T15:16:39.447906+03:00",
            "is_informed": false,
            "patient": 5
        },
        {
            "id": 3,
            "med": {
                "id": 27,
                "title": "missed",
                "dose": 34.0,
                "dose_type": "ml",
                "type": "pill",
                "strict_status": false,
                "food": "While eating",
                "patient": 5,
                "schedule": 35
            },
            "date": "2023-04-24T15:18:21.385091+03:00",
            "is_informed": false,
            "patient": 5
        }
    ]
}`

2023-04-26 06:20 UTC, AHTOH2001 requested changes
Also:
1. Remove all code comments
2. Merge with main

2023-04-26 06:20 UTC, AHTOH2001 commented on api/managment/views.py
> +            return PatientSetting.objects.filter(patient=user.patient)
Should be 404 instead of 500
![image](https://user-images.githubusercontent.com/61160614/234480874-12ac76d5-95d4-4b9a-8f96-2b4a649cba59.png)

2023-04-26 06:20 UTC, AHTOH2001 commented on api/choices.py
![image](https://user-images.githubusercontent.com/61160614/234483317-73bf8f74-0983-436e-8bcb-3c5208996045.png)

**But**
![image](https://user-images.githubusercontent.com/61160614/234483583-7787f3b5-11bb-42e2-ad3e-9d965c4c70d9.png)

2023-04-26 06:20 UTC, AHTOH2001 commented on api/managment/views.py
> +            return PatientSetting.objects.all()
Just notice that we don't need logic of superuser. But you can leave this code

2023-04-26 06:20 UTC, AHTOH2001 commented on api/choices.py
![image](https://user-images.githubusercontent.com/61160614/234484892-8c006ae5-ed5b-485d-8089-b1271e4112e0.png)

**But**
![image](https://user-images.githubusercontent.com/61160614/234484963-765068e2-33a3-4a12-8e4e-4d314f375c0b.png)

2023-05-01 08:24 UTC, AHTOH2001 requested changes
Format with black new code

2023-05-01 08:24 UTC, AHTOH2001 commented on api/managment/serializers.py
> +    relationship = serializers.CharField(max_length=128, min_length=8)
Remove

2023-05-01 08:24 UTC, AHTOH2001 commented on api/managment/views.py
> +            res["user"] = UserSerializer(user).data
Revert as in the master
![image](https://user-images.githubusercontent.com/61160614/235427156-453d734d-f29e-47b0-b5bd-5a30f4325acb.png)

2023-05-01 08:24 UTC, AHTOH2001 commented on api/managment/views.py
> +        return Response({}, status=status.HTTP_201_CREATED)
Нужно делать проверку 6-ти значного кода

2023-05-01 08:24 UTC, AHTOH2001 commented on ml.py
Remove this file

2023-05-01 09:16 UTC, sviridchik commented on ml.py
noooooo

2023-05-01 11:35 UTC, AHTOH2001 approved these changes

2023-05-01 11:57 UTC, merged